(function(root){'use strict';const P=root.SPUD,D=P.data,S=P.sim,N=P.net,U=P.ui;let session=null,lobby=null,renderer=null,uid='solo',mode='title',localPlayer=null,offers=null,rewarded=false,last=0,keys=new Set(),stick=null,roster={players:[],hostUser:null},pendingResync=null;P.sfx=()=>{};
function getUid(){try{let v=localStorage.getItem('spud_uid');if(!v){v='u-'+Math.random().toString(36).slice(2,10);localStorage.setItem('spud_uid',v)}return v}catch{return 'u-'+Math.random().toString(36).slice(2,10)}}
function scene(){if(session?.isHost)return session.world;const snap=session?.buffer.sample(Date.now());if(!snap||!localPlayer)return snap;return {...snap,pl:snap.pl.map(row=>row[0]===uid?[row[0],Math.round(localPlayer.x),Math.round(localPlayer.y),...row.slice(3)]:row)}}
function selected(char){mode='select-wait';P.ui.show('<h2>🥔 준비 중…</h2>');if(session.isHost){session.local({type:'PICK',payload:{uid,char}})}else session.local({type:'PICK',payload:{uid,char}})}
function beginSolo(){uid='solo';session=new N.Session({uid,host:uid,rng:Math.random,onAction:handleAction,onEnd:finish,sendRt:a=>renderer.fx(a.fx,uid)});session.roster({players:[{user:uid}],hostUser:uid});mode='select';U.choose(selected)}
function connect(){uid=getUid();mode='lobby';lobby=new MultiplayerLobby({gameType:'spudsquad',gameName:'감자특공대',minPlayers:1,maxPlayers:4,userId:uid,walletReady:walletPromise,onGameEvent(type,ev){if(type==='event'){const a=ev?.data;if(a?.type==='__resync'&&a.__snapshot){pendingResync=a.__snapshot;if(session)session.receive({type:'WAVE_START',payload:a.__snapshot});else if(lobby?._roster?.started)setTimeout(()=>onRosterChanged(lobby._roster),0);return}if(a?.type)session?.receive(a,ev.seq)}},onLeave(){reset()},onLocal(){beginSolo()}});const wrap=()=>{const ws=lobby._ws;if(!ws||ws._spudHook)return false;ws._spudHook=true;const started=ws.onStarted;ws.onStarted=d=>{started?.(d);onStarted(d)};const onRoster=ws.onRoster;ws.onRoster=d=>{onRoster?.(d);roster=d;onRosterChanged(d)};ws.onRt=(from,data)=>session?.rt(from,data);if(lobby._roster?.started)onRosterChanged(lobby._roster);return true};const poll=setInterval(()=>{if(wrap()||mode==='title')clearInterval(poll)},50)}
function onStarted(d){const host=roster.hostUser||d.players?.[0]||uid;session=new N.Session({uid,host,sendAction:a=>lobby._ws.sendAction(a),sendRt:a=>{renderer.fx(a.fx,uid);lobby._ws.sendRt(a)},onSnapshot:a=>renderer.fx(a.fx,uid),onAction:handleAction,onEnd:finish});session.sendAction.echo=true;session.roster(roster.players?.length?roster:{players:(d.players||[uid]).map(user=>({user})),hostUser:host});mode='select';U.choose(selected);if(session.isHost)setTimeout(()=>{if(session&&session.wave===0){for(const id of Object.keys(session.players))if(!session.pick[id])session.pick[id]='basic';session.start(1)}},20000)}
function onRosterChanged(d){if(!session&&d.started&&pendingResync){onStarted({players:d.players.map(p=>p.user)});session.receive({type:'WAVE_START',payload:pendingResync});pendingResync=null}const oldHost=session?.host;session?.roster(d);if(!session||!session.wave)return;if(oldHost&&oldHost!==d.hostUser&&uid!==oldHost){mode='end';U.show('<h2>호스트가 나갔습니다</h2><button class="btn" id="returnLobby">대기실로</button>');document.getElementById('returnLobby').onclick=()=>{lobby?.goToWaitingRoom();reset()}}}
function handleAction(a){if(a.type==='WAVE_START'){mode='wave';offers=(offers||[]).map(o=>o.locked?o:null);U.hide();if(!session.isHost){const data=a.payload.players[uid];localPlayer=S.createPlayer(uid,data?.char||'basic',data||{});session.buffer.a=[]}}if(a.type==='WAVE_END'){mode='shop';const p=session.world?.players[uid]||localPlayer;const levelUps=a.payload.players?.[uid]?.levelUps||0;if(p){p.mats=a.payload.players?.[uid]?.mats??p.mats;p.levelUps=levelUps;U.upgrades(p,()=>U.shop(session,uid,ready))}else U.shop(session,uid,ready);if(session.isHost)setTimeout(()=>{if(session&&session.wave===a.payload.w&&(mode==='shop'||mode==='ready'))session.next()},45000)}if(a.type==='READY'&&mode==='shop'&&session.isHost&&session.ready.size===Object.keys(session.players).length)session.next()}
function ready(p){session.local({type:'READY',payload:{uid,loadout:{weapons:p.weapons,items:p.items,stats:p.stats,mats:p.mats}}});mode='ready';P.ui.show('<h2>동료를 기다리는 중…</h2>')}
function finish(data){if(mode==='end')return;mode='end';U.result(data,()=>{if(lobby){lobby.goToWaitingRoom();reset()}else reset()});if(!rewarded){rewarded=true;const gold=(data.win?data.wave:Math.max(0,data.wave-1))*30+(data.win?500:0);try{if(typeof SharedWallet!=='undefined'&&SharedWallet.addGold)SharedWallet.addGold(gold,'spudsquad')}catch(e){console.warn('reward pending',e)}try{GameRankings.submit('spudsquad',{score:data.wave*1000+Object.values(data.kills||{}).reduce((a,b)=>a+b,0)})}catch(e){console.warn('rank pending',e)}}}
function reset(){session=null;mode='title';rewarded=false;U.title(a=>a==='solo'?beginSolo():connect())}
function move(dt){const p=session.isHost?session.world?.players[uid]:localPlayer;if(!p||!p.alive)return;let dx=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),dy=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);if(stick){dx+=stick.dx;dy+=stick.dy}const len=Math.hypot(dx,dy);if(len>0){dx/=Math.max(1,len);dy/=Math.max(1,len);p.f=dx<0?-1:1;p.x=S.clamp(p.x+dx*200*(1+p.stats.speed/100)*dt,0,D.W);p.y=S.clamp(p.y+dy*200*(1+p.stats.speed/100)*dt,0,D.H)}if(!session.isHost)return {dx,dy,x:p.x,y:p.y,f:p.f,move(){}}}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.1,(now-last)/1000||0);last=now;if(session&&mode==='wave'){if(session.isHost){move(dt);session.update(dt)}else{const input=move(dt);session.update(dt,input)}const v=scene();if(v){U.hud(v,uid);renderer.draw(v,uid,now);}}else if(renderer)renderer.draw(null,uid,now)}
let walletPromise;document.addEventListener('DOMContentLoaded',()=>{walletPromise=typeof SharedWallet!=='undefined'?SharedWallet.init():Promise.resolve();renderer=new P.render.Renderer(document.getElementById('canvas'));try{GameRankings.injectNavButton('spudsquad')}catch(e){console.warn('rank nav unavailable',e)}reset();requestAnimationFrame(frame);if(new URLSearchParams(location.search).has('room'))connect()});window.addEventListener('keydown',e=>{keys.add(e.key.length===1?e.key.toLowerCase():e.key);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));const canvas=document.getElementById('canvas');canvas.addEventListener('pointerdown',e=>{stick={x:e.clientX,y:e.clientY,dx:0,dy:0};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(stick){stick.dx=S.clamp((e.clientX-stick.x)/60,-1,1);stick.dy=S.clamp((e.clientY-stick.y)/60,-1,1)}});canvas.addEventListener('pointerup',()=>stick=null);document.addEventListener('visibilitychange',()=>{last=performance.now()});P.main={get session(){return session},get localPlayer(){return localPlayer},get offers(){return offers},set offers(v){offers=v},refresh(){if(mode==='title')reset()}};
})(window);
